### ISSUE TITLE
Change Button Colour Dynamically / Multiple Buttons

### ISSUE THREAD

**Issue by shaneparsons** [alertifyjs/alertify.js#27]
Correct me if I'm wrong, but it looks like you're resurrecting alertify?

If so, the following is an feature request I posted on the master branch (after maintenance was discontinued)

>I think it would be great to be able to change the button colour of the `alertify-button-ok` and `alertify-button-cancel` **dynamically**.

>E.g. A dialog window for a "delete" task in my opinion should have a **red** `alertify-button-ok` where a dialog for a more "positive/safe" task can have  a **green** `alertify-button-ok`.

>I've been able to work around this is by appending inline styles to the `<head>` that override the alertify's css, but I still think it would be great to have it as an option in the plugin itself.

Keep up the good work!

**Comment by bradberger** [comment]
You're right, it's being maintained here.

The request makes sense, and I think it's something that would be useful. Right now, it seems that it would be great for the next upcoming branch. Everything's going to get a major rewrite, so it would make sense to put it there.

**Comment by shaneparsons** [comment]
Perfect, that's great to hear!
Thanks!

**Comment by shaneparsons** [comment]
@bradberger I personally don't know if we need this anymore, but I'm interested to know what you think.

I'm personally quite fond of the new style of alertify.js, i.e. the colourless buttons, and figure it's easy enough to append a `.alertify-button-ok { background: green; }` to the head anyways.

Let me know.

**Comment by bradberger** [comment]
Yeah, think you might be right again. 

One thing that I've had in mind and would still like to get implemented is allowing the whole template to change dynamically, which would take care of all of that. It would be something like:

```
alertify
    .setAlertTemplate("<div>content-here</div>")
    .alert("Hello, world");
```

That would allow for custom buttons, styles, etc. Right now the html for some parts of the dialogs/etc. would be [very easy to change](https://github.com/alertifyjs/alertify.js/blob/master/src/js/alertify.js#L49), as with the latest version it's part of the `alertify._$$alertify` "private" class, so someone "in the know" could actually change it (for example to be a real bootstrap styled buttons:

```javascript
alertify._$$alertify.dialogs.buttons.ok = "<button class='ok btn btn-success' tabindex='-1'>{{ok}}</button>";
alertify._$$alertify.dialogs.buttons.cancel = "<button class='cancel btn btn-danger' tabindex='-1'>{{cancel}}</button>";
</button>
```

The underlying code actually just looks for a child `.ok` class and attaches the event listeners to that, so any other classes can be added to customize things.

That being said, I don't think it's a particularly good idea for people to go around altering the private sections of the code, so that's why I think a public method to change the template (and reset it again with the `reset()` method) would be useful. Plus, there would have to be some more documentation about setting a custom template, too, to know how it's parsed.

The above is actually the reason we recently pulled the themes from the website, as it would be much better to integrate an option to switch to buttons with real classes for the various frameworks, like Bootstrap, Pure CSS, Material Design Light, etc. so that it wouldn't be just imitating the default style but would actually integrate the user's custom styles.

```javascript
// Bootstrap
alertify._$$alertify.dialogs.buttons.ok = "<button class='ok btn btn-success' tabindex='-1'>{{ok}}</button>";
// Pure CSS
alertify._$$alertify.dialogs.buttons.ok = "<button class='ok pure-button' tabindex='-1'>{{ok}}</button>";
// Material Design Light
alertify._$$alertify.dialogs.buttons.ok = "<button class='ok mdl-button mdl-js-button mdl-js-ripple-effect'>{{ok}}</button>";
// Angular Material
alertify._$$alertify.dialogs.buttons.ok = "<button class='ok md-raised md-primary md-button md-default-theme'>{{ok}}</button>";
// etc..
```

The templates themselves are [implemented here right now](https://github.com/alertifyjs/alertify.js/blob/master/src/js/alertify.js#L49) if you want to check it out.

If we wanted to support some basic frameworks by default, I also thought it might be easier to do it for the user, too, perhaps something like this, and behind the scenes we'd change the templates manually:

```javascript
alertify.useBootstrapTheme();
alertify.usePureCSSTheme();
// etc...
```

But it's all a question of finding the time to design/implement it :smile: Feedback is always welcomed. It might be good to get a discussion going around this idea of templating/changing the default styles and how we can do that best. Those are just a few ideas, but I'm sure other people would come up with some great solutions, too.

**Comment by bradberger** [comment]
Going to close this for now, as it's more a part of issue #50 now

**Comment by brianespinosa** [comment]
@bradberger It would make sense if you could do something like this:

`alertify
  .okBtn("Remove")
  .okBtnClass("cancel")
  .cancelBtn("Cancel")
  .cancelBtnClass("tertiary")
  .confirm('Are you sure you want to remove from the team?')`

This way you could easily switch the classes around. Right now in my styles I have the `.ok` class set to a green background and the `.cancel` class to a red. It would be great to be able to set another class in the way shown above as it pertains to the UI.

**Comment by tnrich** [comment]
Similar to the above, I'd like to have the ability to add a class to the alert itself. Perhaps something like this: 

```
alertify
  .log("Some message")
  .class('myLogClass')
```
